apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sample-app1"
  labels:
    app: "sample-app1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sample-app1"
  template:
    metadata:
      labels:
        app: "sample-app1"
    spec:
      containers:
      - name: "sample-api-image-1"
        image: "gcr.io/hackathon-project-1/sample-api-image:latest"
