apiVersion: "v1"
kind: "Service"
metadata:
  name: "apache-tomcat-service"
  labels:
    app: "apache-tomcat"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "apache-tomcat"
  type: "LoadBalancer"
  loadBalancerIP: ""
